streams:
  - btcusdt@aggTrade
  - btcusdt@depth
sinks:
  - type: console
  - type: file
    file:
      path: output.json
  - type: http
    http:
      url: http://localhost:8080
      method: POST
      content_type: application/json
